# application.yml
server:
  port: 8081

spring:
  application:
    name: payment-outbox-pattern

  # Database Configuration for PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # In a real production scenario, we would use a migration tool like Flyway or Liquibase
    show-sql: true

  # Kafka Configuration
  kafka:
    # Producer settings
    producer:
      bootstrap-servers: localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    # Consumer settings
    consumer:
      bootstrap-servers: localhost:9092
      group-id: payment-processor
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*' # Trust all packages for deserialization (for development)
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.payment.service.events.PaymentCreatedEvent
